config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get 'homes/top', as:'/'
  resources :books,except: [:new,]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
    @book = Book.new
  end

  def create         # インデックス画面で Create Book ボタンを押したときに呼び出されるアクション
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book was successfully created."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    book = Book.find(params[:id])
    if book.update(book_params)
      flash[:notice] = "Book was successfully updated."
      redirect_to book_path(book.id)
    else
      @book = book
      render :show
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end


private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<div class ="edit">
  <h2>Editing Book</h2>

  <%= form_with model: @book do |f| %>

    <p>Title</p>
    <%= f.text_field :title %>

    <p>Body</p>
    <%= f.text_area :body %>

    <p><%= f.submit 'Update Book' %></p>

  <% end %>

  <p><%= link_to "Show", book_path(@book.id) %> | <%= link_to "Back", books_path %></p>
</div>

app/views/books/index.html.erb
<!-- インデックスページでbooksの中身一覧表示 -->

<div class ="index">
  <h1>Books</h1>  

  <table>
    <tr>
      <th>Title</th>
      <th>Body</th>
    </tr>

    <% @books.each do |book| %>

      <tr>
        <td><%= book.title %></td>
        <td><%= book.body %></td>

        <td><%= link_to "Show", book_path(book.id) %></td>

        <td><%= link_to "Edit", edit_book_path(book.id) %></td>

        <td><%= link_to "Destroy", book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %></td>
      </tr>

    <% end %>

  </table>



  <!-- ここから下新規投稿コード -->
  <div class ="new-book">
    <h3>New book</h3> 

    <!-- バリデーションエラー検出時 -->
    <% if @book.errors.any? %>
      <div class ="error">
        <div class ="error-box">
          <span><b><%= @book.errors.count %> errors prohibited this book from being saved:</b></span>
          <div class ="error-box-item">
            <% @book.errors.full_messages.each do |message| %>
              <ul>
                <li><%= message %></li>
              </ul>
            <% end %>
          </div>
        </div>
        <%= form_with model: @book, url: '/books', method: :post  do |f| %>
          <p>Title</p>
          <%= f.text_field :title %>
          <p>Body</p>
          <%= f.text_area :body %>
          <p><%= f.submit 'Create Book' %></p>
        <% end %>
      </div>     
      
      <!-- 通常時  新規投稿 -->
    <% else %>
      <%= form_with model: @book, url: '/books', method: :post  do |f| %>
        <p>Title</p>
        <%= f.text_field :title %>
        <p>Body</p>
        <%= f.text_area :body %>
        <p><%= f.submit 'Create Book' %></p>          
      <% end %>
    <% end %>
  </div>
</div>

app/views/books/show.html.erb
<div class ="show">
  <!-- エディットページでバリデーションエラー検出時 -->

  <%if @book.errors.any? %>
    <h1>Editing Book</h1>
    <div class ="error">
      <div class ="error-box">
        <span><b><%= @book.errors.count %> errors prohibited this book from being saved:</b></span>
        <div class ="error-box-item">
          <% @book.errors.full_messages.each do |message| %>
            <ul>
              <li><%= message %></li>
            </ul>
          <% end %>
        </div>
      </div>
      <%= form_with model: @book do |f| %>
        <div class ="show-error-new">
          <p>Title</p>
          <%= f.text_field :title %>
          <p>Body</p>
          <%= f.text_area :body %>
          <p><%= f.submit 'Update Book' %></p>
          <%= link_to "Show", book_path(@book.id) %> | <%= link_to "Back", books_path %>
        </div>
      <% end %>
    </div>

      <!-- 通常時showページ -->
  <% else %>
    <p class ="flash"><%= flash[:notice] %></p>
   <div class="show-main">  
      <p><b>Title: </b><%= @book.title %></p>
      <p><b>Body: </b><%= @book.body %></p>
      <%= link_to "Edit", edit_book_path(@book.id) %> | <%= link_to "Back", books_path %>
    </div>
  <% end %>
</div>

app/views/homes/top.html.erb
<div class ="top">
  <h2>ようこそ Bookers へ！</h2>
  <p><b>Bookers</b> では、さまざまな書籍に関するあなたの意見や</p>
  <p>印象を共有し交換することができます</p>
  <a href="/books">start</a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>